export const SECTOR_OPTIONS: string[] = [
  "Holding",
  "Retail y Consumo",
  "Logistica y Transporte",
  "Tecnologia y SaaS",
  "Manufactura",
  "Servicios Financieros",
  "Construccion e Infraestructura",
  "Salud y Farmaceutico",
  "Educacion",
  "Energia y Utilities",
  "Agroindustria",
  "Gobierno y Sector Publico",
  "ONG y Fundaciones",
  "Hoteleria y Turismo",
  "Telecomunicaciones",
  "Seguros",
  "Mineria",
  "Inmobiliario",
  "Medios y Entretenimiento",
];
