export const SECTOR_OPTIONS: string[] = [
  "Holding",
  "Servicios Legales",
  "Servicios Profesionales",
  "Retail y Consumo",
  "Logística y Transporte",
  "Tecnología y SaaS",
  "Manufactura",
  "Servicios Financieros",
  "Construcción e Infraestructura",
  "Salud y Farmacéutico",
  "Educación",
  "Energía y Utilities",
  "Agroindustria",
  "Gobierno y Sector Público",
  "ONG y Fundaciones",
  "Hotelería y Turismo",
  "Telecomunicaciones",
  "Seguros",
  "Minería",
  "Inmobiliario",
  "Medios y Entretenimiento",
];
