/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clientes */
        get: operations["get_clientes_clientes_get"];
        put?: never;
        /** Post Cliente */
        post: operations["post_cliente_clientes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Cliente */
        delete: operations["remove_cliente_clientes__cliente_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/upload/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Cliente File */
        post: operations["upload_cliente_file_clientes__cliente_id__upload__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cliente Documentos */
        get: operations["get_cliente_documentos_clientes__cliente_id__documentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/documentos/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Cliente Documento */
        post: operations["upload_cliente_documento_clientes__cliente_id__documentos_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/hallazgos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cliente Hallazgos */
        get: operations["get_cliente_hallazgos_clientes__cliente_id__hallazgos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/documentos/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cliente Documento File */
        get: operations["get_cliente_documento_file_clientes__cliente_id__documentos_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/perfil/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Perfil */
        get: operations["get_perfil_perfil__cliente_id__get"];
        /** Put Perfil */
        put: operations["put_perfil_perfil__cliente_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_dashboard__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk-engine/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Engine */
        get: operations["get_risk_engine_risk_engine__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{cliente_id}/{area_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Area */
        get: operations["get_area_areas__cliente_id___area_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{cliente_id}/{area_code}/cuentas/{cuenta_codigo}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Check */
        patch: operations["patch_check_areas__cliente_id___area_code__cuentas__cuenta_codigo__check_patch"];
        trace?: never;
    };
    "/areas/{cliente_id}/{area_code}/conclusion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Conclusion */
        put: operations["put_conclusion_areas__cliente_id___area_code__conclusion_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["post_chat_chat__cliente_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{cliente_id}/metodologia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Metodologia */
        post: operations["post_metodologia_chat__cliente_id__metodologia_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/metodologia/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Metodologia Alias */
        post: operations["post_metodologia_alias_chat_metodologia__cliente_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{cliente_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat Export */
        post: operations["post_chat_export_chat__cliente_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metodologia/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Metodologia Endpoint */
        post: operations["metodologia_endpoint_metodologia__cliente_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/{cliente_id}/executive-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Executive Pdf */
        get: operations["get_executive_pdf_reportes__cliente_id__executive_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/{cliente_id}/executive-pdf/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Executive Pdf File */
        get: operations["get_executive_pdf_file_reportes__cliente_id__executive_pdf_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/{cliente_id}/memo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Executive Memo */
        get: operations["get_executive_memo_reportes__cliente_id__memo_get"];
        put?: never;
        /** Post Executive Memo */
        post: operations["post_executive_memo_reportes__cliente_id__memo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/{cliente_id}/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report History */
        get: operations["get_report_history_reportes__cliente_id__historial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papeles-trabajo/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workpapers */
        get: operations["get_workpapers_papeles_trabajo__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papeles-trabajo/{cliente_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Workpaper Task */
        patch: operations["patch_workpaper_task_papeles_trabajo__cliente_id__tasks__task_id__patch"];
        trace?: never;
    };
    "/papeles-trabajo/{cliente_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Workpaper Task */
        post: operations["post_workpaper_task_papeles_trabajo__cliente_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow State */
        get: operations["get_workflow_state_workflow__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/{cliente_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Workflow */
        post: operations["advance_workflow_workflow__cliente_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiMeta */
        ApiMeta: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** ApiResponse */
        ApiResponse: {
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "error";
            /** Data */
            data: unknown;
            meta?: components["schemas"]["ApiMeta"];
        };
        /** AreaCheckRequest */
        AreaCheckRequest: {
            /** Checked */
            checked: boolean;
        };
        /** AreaConclusionRequest */
        AreaConclusionRequest: {
            /** Conclusion */
            conclusion: string;
        };
        /** AreaRiesgo */
        AreaRiesgo: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Score Riesgo */
            score_riesgo: number;
            /** Prioridad */
            prioridad: string;
            /** Saldo Total */
            saldo_total: number;
            /** Con Saldo */
            con_saldo: boolean;
        };
        /** BalanceKPIs */
        BalanceKPIs: {
            /**
             * Activo
             * @description Total activos
             * @default 0
             */
            activo: number;
            /**
             * Pasivo
             * @description Total pasivos
             * @default 0
             */
            pasivo: number;
            /**
             * Patrimonio
             * @description Patrimonio neto
             * @default 0
             */
            patrimonio: number;
            /**
             * Ingresos
             * @description Ingresos del periodo
             * @default 0
             */
            ingresos: number;
            /**
             * Gastos
             * @description Gastos del periodo
             * @default 0
             */
            gastos: number;
        };
        /** Body_upload_cliente_documento_clientes__cliente_id__documentos_upload_post */
        Body_upload_cliente_documento_clientes__cliente_id__documentos_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_cliente_file_clientes__cliente_id__upload__kind__post */
        Body_upload_cliente_file_clientes__cliente_id__upload__kind__post: {
            /** File */
            file: string;
        };
        /** ChatExportRequest */
        ChatExportRequest: {
            /** Content */
            content: string;
            /** Title */
            title?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /** ClienteCreateRequest */
        ClienteCreateRequest: {
            /** Cliente Id */
            cliente_id?: string | null;
            /** Nombre */
            nombre: string;
            /** Sector */
            sector?: string | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Cliente Id */
            cliente_id: string;
            /** Nombre Cliente */
            nombre_cliente: string;
            /** Periodo */
            periodo: string;
            /** Sector */
            sector: string;
            /** Riesgo Global */
            riesgo_global: string;
            balance: components["schemas"]["BalanceKPIs"];
            progreso: components["schemas"]["ProgresoEncargo"];
            /** Top Areas */
            top_areas: components["schemas"]["AreaRiesgo"][];
            /**
             * Materialidad Global
             * @default 0
             */
            materialidad_global: number;
            /**
             * Materialidad Ejecucion
             * @default 0
             */
            materialidad_ejecucion: number;
            /**
             * Umbral Trivial
             * @default 0
             */
            umbral_trivial: number;
            /**
             * Materialidad Origen
             * @default
             */
            materialidad_origen: string;
            /**
             * Fase Actual
             * @default
             */
            fase_actual: string;
            /**
             * Workflow Phase
             * @default planificacion
             */
            workflow_phase: string;
            /** Workflow Gates */
            workflow_gates?: components["schemas"]["DashboardWorkflowGate"][];
        };
        /** DashboardWorkflowGate */
        DashboardWorkflowGate: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "blocked";
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MetodoRequest */
        MetodoRequest: {
            /** Area */
            area: string;
        };
        /** ProgresoEncargo */
        ProgresoEncargo: {
            /**
             * Pct Completado
             * @default 0
             */
            pct_completado: number;
            /**
             * Areas Completas
             * @default 0
             */
            areas_completas: number;
            /**
             * Areas En Proceso
             * @default 0
             */
            areas_en_proceso: number;
            /**
             * Areas No Iniciadas
             * @default 0
             */
            areas_no_iniciadas: number;
            /**
             * Total Areas
             * @default 0
             */
            total_areas: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowAdvanceRequest */
        WorkflowAdvanceRequest: {
            /** Target Phase */
            target_phase?: string | null;
        };
        /** WorkpaperTaskCreateRequest */
        WorkpaperTaskCreateRequest: {
            /** Area Code */
            area_code: string;
            /** Area Name */
            area_name: string;
            /** Title */
            title: string;
            /**
             * Nia Ref
             * @default
             */
            nia_ref: string;
            /**
             * Prioridad
             * @default media
             */
            prioridad: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Evidence Note
             * @default
             */
            evidence_note: string;
        };
        /** WorkpaperTaskUpdateRequest */
        WorkpaperTaskUpdateRequest: {
            /** Done */
            done: boolean;
            /**
             * Evidence Note
             * @default
             */
            evidence_note: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clientes_clientes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    post_cliente_clientes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_cliente_clientes__cliente_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cliente_file_clientes__cliente_id__upload__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cliente_file_clientes__cliente_id__upload__kind__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cliente_documentos_clientes__cliente_id__documentos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cliente_documento_clientes__cliente_id__documentos_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cliente_documento_clientes__cliente_id__documentos_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cliente_hallazgos_clientes__cliente_id__hallazgos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cliente_documento_file_clientes__cliente_id__documentos_file_get: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_perfil_perfil__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_perfil_perfil__cliente_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_dashboard__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_engine_risk_engine__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_area_areas__cliente_id___area_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
                area_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_check_areas__cliente_id___area_code__cuentas__cuenta_codigo__check_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
                area_code: string;
                cuenta_codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_conclusion_areas__cliente_id___area_code__conclusion_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
                area_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaConclusionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_chat__cliente_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_metodologia_chat__cliente_id__metodologia_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetodoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_metodologia_alias_chat_metodologia__cliente_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetodoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_export_chat__cliente_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metodologia_endpoint_metodologia__cliente_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetodoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_executive_pdf_reportes__cliente_id__executive_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_executive_pdf_file_reportes__cliente_id__executive_pdf_file_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_executive_memo_reportes__cliente_id__memo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_executive_memo_reportes__cliente_id__memo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_history_reportes__cliente_id__historial_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workpapers_papeles_trabajo__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_workpaper_task_papeles_trabajo__cliente_id__tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkpaperTaskUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_workpaper_task_papeles_trabajo__cliente_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkpaperTaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_state_workflow__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_workflow_workflow__cliente_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
