ASEVERACIONES_LS = {
    "140": ["existencia", "integridad", "derechos", "presentacion"],
    "141": ["existencia", "valuacion", "derechos"],
    "130.1": ["existencia", "valuacion", "derechos", "corte"],
    "130.2": ["existencia", "valuacion", "derechos"],
    "35": ["existencia", "valuacion", "derechos"],
    "120": ["existencia", "valuacion"],
    "110": ["existencia", "valuacion", "integridad", "corte"],
    "135": ["existencia", "valuacion", "presentacion"],
    "136": ["existencia", "valuacion"],
    "111": ["existencia", "valuacion"],
    "1": ["existencia", "valuacion", "derechos", "presentacion"],
    "10": ["existencia", "valuacion", "derechos"],
    "11": ["existencia", "valuacion", "derechos"],
    "5": ["existencia", "valuacion"],
    "12": ["existencia", "valuacion"],
    "14": ["existencia", "valuacion", "derechos"],
    "15": ["existencia", "valuacion"],
    "16": ["existencia", "valuacion"],
    "425": ["integridad", "obligaciones", "valuacion", "corte"],
    "425.1": ["integridad", "obligaciones", "valuacion"],
    "425.2": ["integridad", "obligaciones", "valuacion"],
    "300.1": ["integridad", "obligaciones", "valuacion"],
    "300.2": ["integridad", "obligaciones", "valuacion"],
    "310": ["integridad", "obligaciones", "valuacion"],
    "310.1": ["integridad", "obligaciones", "valuacion"],
    "324": ["integridad", "valuacion"],
    "325": ["integridad", "valuacion"],
    "410": ["integridad", "obligaciones", "valuacion"],
    "415": ["integridad", "obligaciones", "valuacion"],
    "420": ["integridad", "valuacion"],
    "421": ["integridad", "valuacion"],
    "430": ["integridad", "valuacion"],
    "200": ["integridad", "presentacion", "derechos"],
    "1500": ["integridad", "ocurrencia", "corte"],
    "1501": ["integridad", "ocurrencia"],
    "1600.5": ["integridad", "valuacion", "corte"],
    "1600": ["integridad", "valuacion", "presentacion"],
    "1700": ["integridad", "valuacion", "presentacion"],
    "1701": ["integridad", "valuacion", "presentacion"],
    "1601": ["integridad", "valuacion"],
    "1800": ["integridad", "valuacion", "presentacion"],
    "1900": ["integridad", "valuacion", "presentacion"],
}